apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpn
  labels:
    app: vpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpn
  template:
    metadata:
      labels:
        app: vpn
    spec:
      volumes:
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
        - name: openvpn-conf
          secret:
            secretName: openvpn
      containers:
        - name: vpn
          image: "ghcr.io/axle-h/make-movies-openvpn:latest"
          imagePullPolicy: Always
          volumeMounts:
            - name: dev-net-tun
              mountPath: /dev/net/tun
            - name: openvpn-conf
              mountPath: /etc/openvpn/client
              readOnly: true
          securityContext:
            privileged: true
            capabilities:
                add: ["NET_ADMIN"]
          ports:
            - name: socks
              containerPort: 1080
          livenessProbe:
            exec:
              command:
              - curl
              - --fail
              - -s
              - --socks5-hostname
              - localhost:1080
              - ipinfo.io/ip
            periodSeconds: 3600 # uses internet IO
          startupProbe:
            tcpSocket:
              port: socks
            failureThreshold: 10
            periodSeconds: 10
