version: '2.4'

services:
  mysql:
    image: mysql:8.0.19
    restart: always
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']
    environment:
      - MYSQL_ROOT_PASSWORD=root-password
    ports:
      - 3307:3306

  api:
    build: .
    restart: always
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Production}
      - CONNECTIONSTRINGS__MYSQL=Server=mysql;Port=3306;Database=MolliesMovies;Uid=root;Pwd=rootpassword;
      - CONNECTIONSTRINGS__PLEX=http://${DOCKER_HOST_IP:-docker.host.internal}:32400
      - CONNECTIONSTRINGS__TRANSMISSION=http://${DOCKER_HOST_IP:-docker.host.internal}:9091/transmission/rpc
    ports:
      - 6000:80