// <auto-generated/>
#pragma warning disable CS0618
using MakeMovies.Api.Meta.Tmdb.Three.Configuration;
using MakeMovies.Api.Meta.Tmdb.Three.Find;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MakeMovies.Api.Meta.Tmdb.Three
{
    /// <summary>
    /// Builds and executes requests for operations under \3
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ThreeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The configuration property</summary>
        public global::MakeMovies.Api.Meta.Tmdb.Three.Configuration.ConfigurationRequestBuilder Configuration
        {
            get => new global::MakeMovies.Api.Meta.Tmdb.Three.Configuration.ConfigurationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The find property</summary>
        public global::MakeMovies.Api.Meta.Tmdb.Three.Find.FindRequestBuilder Find
        {
            get => new global::MakeMovies.Api.Meta.Tmdb.Three.Find.FindRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MakeMovies.Api.Meta.Tmdb.Three.ThreeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ThreeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MakeMovies.Api.Meta.Tmdb.Three.ThreeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ThreeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
