version: '3.1'

services:
  wiremock:
    image: rodolpheche/wiremock
    ports:
      - "8080:8080"
    volumes:
      - ./stubs/wiremock/mappings:/home/wiremock/mappings
      - ./stubs/wiremock/__files:/home/wiremock/__files
    command:
      - -verbose
      - --enable-stub-cors

  app:
    build: .
    depends_on:
      - wiremock
    ports:
      - "5000:80"
