version: '2.4'

services:
  mongo:
    image: mongo:5
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 15672:15672
      - 5672:5672

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    restart: unless-stopped
    depends_on:
      - mongo
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Production}
      - CONNECTIONSTRINGS__RABBITMQ=rabbitmq://user:password@rabbitmq:5672
      - CONNECTIONSTRINGS__MONGO=mongodb://mongo:27017/mollys-movies
      - CONNECTIONSTRINGS__TRANSMISSION=http://transmission:9091/transmission/
    ports:
      - 5000:80
        
  scraper:
    build:
      context: .
      dockerfile: scraper.Dockerfile
    restart: unless-stopped
    depends_on:
      - mongo
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Production}
      - CONNECTIONSTRINGS__RABBITMQ=rabbitmq://user:password@rabbitmq:5672
      - CONNECTIONSTRINGS__MONGO=mongodb://mongo:27017/mollys-movies
      - CONNECTIONSTRINGS__PLEX=http://10.0.0.10:32400/
      - CONNECTIONSTRINGS__TRANSMISSION=http://transmission:9091/transmission/
      - SCRAPER__PLEX__TOKEN=some-plex-token
    ports:
      - 5001:80

  transmission:
    build:
      context: .
      dockerfile: transmission.Dockerfile
    restart: unless-stopped
    depends_on:
      - rabbitmq
    environment:
      - CONNECTIONSTRINGS__RABBITMQ=rabbitmq://user:password@rabbitmq:5672
    ports:
      - 9091:9091
        