nameOverride: ""
fullnameOverride: ""

vpn:
  secret: openvpn
  image:
    repository: ghcr.io/axle-h/make-movies-openvpn
    tag: ""
    pullPolicy: Always
  service:
    type: LoadBalancer
    port: 1080