import nextCoreWebVitals from 'eslint-config-next/core-web-vitals'
import prettierRecommended from 'eslint-plugin-prettier/recommended'

const config = [
  // client/ is generated by kiota, see client/README.md
  { ignores: ['.next/**', 'client/**', 'next-env.d.ts'] },
  ...nextCoreWebVitals,
  prettierRecommended,
  { rules: { 'prettier/prettier': 'warn' } },
]

export default config
