import js from '@eslint/js'
import globals from 'globals'
import tseslint from 'typescript-eslint'
import reactHooks from 'eslint-plugin-react-hooks'
import prettierRecommended from 'eslint-plugin-prettier/recommended'

const config = [
  {
    ignores: [
      'dist/**',
      'src/client/**', // generated by kiota
      'src/routeTree.gen.ts', // generated by the tanstack router plugin
      'mock-api/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  reactHooks.configs.flat['recommended-latest'],
  prettierRecommended,
  {
    languageOptions: {
      globals: globals.browser,
    },
    rules: { 'prettier/prettier': 'warn' },
  },
]

export default config
