// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MakeMovies.Api.Meta.Tmdb.Three.Configuration
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    #pragma warning disable CS1591
    public partial class ConfigurationGetResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The change_keys property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ChangeKeys { get; set; }
#nullable restore
#else
        public List<string> ChangeKeys { get; set; }
#endif
        /// <summary>The images property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MakeMovies.Api.Meta.Tmdb.Three.Configuration.ConfigurationGetResponse_images? Images { get; set; }
#nullable restore
#else
        public global::MakeMovies.Api.Meta.Tmdb.Three.Configuration.ConfigurationGetResponse_images Images { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MakeMovies.Api.Meta.Tmdb.Three.Configuration.ConfigurationGetResponse"/> and sets the default values.
        /// </summary>
        public ConfigurationGetResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MakeMovies.Api.Meta.Tmdb.Three.Configuration.ConfigurationGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MakeMovies.Api.Meta.Tmdb.Three.Configuration.ConfigurationGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::MakeMovies.Api.Meta.Tmdb.Three.Configuration.ConfigurationGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "change_keys", n => { ChangeKeys = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "images", n => { Images = n.GetObjectValue<global::MakeMovies.Api.Meta.Tmdb.Three.Configuration.ConfigurationGetResponse_images>(global::MakeMovies.Api.Meta.Tmdb.Three.Configuration.ConfigurationGetResponse_images.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("change_keys", ChangeKeys);
            writer.WriteObjectValue<global::MakeMovies.Api.Meta.Tmdb.Three.Configuration.ConfigurationGetResponse_images>("images", Images);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
