name: Build
on: [push]
jobs:
  build-test-api:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:10.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Cache nuget packages
        uses: actions/cache@v6
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('api/**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build
        run: dotnet build
        working-directory: api

      - name: Test
        run: dotnet test
        working-directory: api
  
  build-test-ui:
    runs-on: ubuntu-latest
    container: node:24
    env:
      COREPACK_ENABLE_DOWNLOAD_PROMPT: 0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Enable pnpm
        run: corepack enable

      - name: Cache pnpm store
        uses: actions/cache@v6
        with:
          path: ~/.local/share/pnpm/store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('ui/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Restore packages
        run: pnpm install --frozen-lockfile
        working-directory: ui

      - name: Lint
        run: pnpm run lint
        working-directory: ui

      - name: Build
        run: pnpm run build
        working-directory: ui

  docker-vpn:
    needs:
      - build-test-api
      - build-test-ui
    uses: ./.github/workflows/publish-container.yml
    with:
      name: vpn
      context: ./vpn
      file: ./vpn/Dockerfile
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  docker-api:
    needs:
      - build-test-api
      - build-test-ui
    uses: ./.github/workflows/publish-container.yml
    with:
      name: api
      context: .
      file: ./Dockerfile
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
